Image and input
preethasri/OrnateUI pull request #17
Opened 2022-02-03 18:08 UTC by preethasri

2022-02-03 18:24 UTC, vijaytembugade approved these changes
![image](https://user-images.githubusercontent.com/58331578/152404685-ad154c1c-88c6-4464-895d-6e1883805ab7.png)
You can check on google how can we select one radio button at a time. 

Rest things looks perfect. Style other things like navbar and sidebar, which will make look of website better.

2022-02-03 18:42 UTC, msdeshmukh009 requested changes

2022-02-03 18:42 UTC, msdeshmukh009 commented on image component/img.css
> +.library-sidebar {
Hey preetha. I can see that you are writing sidebar styles in multiple stylesheets so it's better to make a separate stylesheet for that and then use it. A component stylesheet should only contain styles related to that respective component.

2022-02-03 18:42 UTC, msdeshmukh009 commented on image component/img.css
> +#image-heading,
I think it's better to avoid id selectors as it is not reusable. Try classes for styling.

2022-02-04 04:53 UTC, preethasri commented on image component/img.css
> +.library-sidebar {
> Hey preetha. I can see that you are writing sidebar styles in multiple stylesheets so it's better to make a separate stylesheet for that and then use it. A component stylesheet should only contain styles related to that respective component.

hey mahesh i thought i can do all these things after finishing the components. anyways thank you for pointing it out.will work on that 👍

2022-02-04 04:54 UTC, preethasri commented
> ![image](https://user-images.githubusercontent.com/58331578/152404685-ad154c1c-88c6-4464-895d-6e1883805ab7.png) You can check on google how can we select one radio button at a time.
> 
> Rest things looks perfect. Style other things like navbar and sidebar, which will make look of website better.

will work on this vijay

2022-02-04 11:12 UTC, MiheerTamkhane commented on image component/img.html
> +
I would recommend ad hiphen or underscore in between spaces of folder name.

2022-02-04 11:13 UTC, MiheerTamkhane approved these changes
Looks good to me, also try to make switchable radio buttons. Nice work

2022-02-04 11:57 UTC, kiranpratyush approved these changes

2022-02-04 13:01 UTC, merged